# Plik konfiguracyjny dla Railway, który rozwiązuje problem z budowaniem

# Poprawiona sekcja 'providers'. Teraz jest to lista.
# Railway automatycznie wykryje wersję z pliku runtime.txt.
providers = ["python"]

# Definiujemy fazę instalacji (setup).
[phases.setup]
# Lista dodatkowych pakietów systemowych, które Railway ma zainstalować.
# Dodajemy poprawną nazwę pakietu "postgresql_16".
pkgs = ["gcc", "postgresql_16"]

